# Generated by Django 4.2.7 on 2023-12-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
