# Generated by Django 4.2.7 on 2023-12-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='user_review',
            field=models.BooleanField(default=False),
        ),
    ]
