# Generated by Django 4.2.7 on 2023-12-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_borrowbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='return_book',
            field=models.BooleanField(default=False),
        ),
    ]
